/**
 * useNutritionState — the diet/water hot path, extracted from AppContext (M4).
 *
 * Owns the derived consumed-nutrition total, the today-diet/history refreshers,
 * and every diet + water handler. State stays owned by the provider and flows in
 * via setters, so this is a pure move: identical bodies, identical dependency
 * arrays, no behavior change.
 */
import { useCallback, useMemo } from "react";
import type { Dispatch, SetStateAction } from "react";

import type { FoodItem } from "../../constants/FoodDictionary";
import type {
  DietHistoryEntry,
  ScheduledMeal,
  TodayDiet,
} from "../../models/diet";
import type { NutritionTargets } from "../../models/nutrition";
import type { PlanState } from "../../models/planState";
import type { UserBio, UserGoals } from "../../models/user";
import type { ConsumedNutrition } from "../AppContext";
import {
  AchievementRecord,
  creditWaterGoalDay,
  saveAchievementRecord,
} from "../../services/AchievementService";
import { calculateConsumedNutrition } from "../../services/DietPlanGenerator";
import {
  KEYS,
  currentWeekStart,
  parseLocalDate,
  todayDate,
  toLocalDateString,
  writeJSON,
} from "../../services/OfflineStorage";
import { ensureDietBuffer, regenerateDietForDate } from "../../services/PlanSync";
import {
  addSnackToSchedule,
  getDietHistory,
  getTodayDiet,
  markMealConsumed,
  swapMealInSchedule,
  toggleMealConsumed,
} from "../../services/ScheduleService";
import { recordActivity, StreakData } from "../../services/StreakService";

interface Params {
  userBio: UserBio | null;
  nutritionTargets: NutritionTargets | null;
  planState: PlanState;
  currentDate: string;
  userGoals: UserGoals;
  todayDiet: TodayDiet | null;
  waterMl: number;
  setTodayDiet: Dispatch<SetStateAction<TodayDiet | null>>;
  setDietHistory: Dispatch<SetStateAction<DietHistoryEntry[]>>;
  setPlanState: Dispatch<SetStateAction<PlanState>>;
  setWaterMl: Dispatch<SetStateAction<number>>;
  setStreakData: Dispatch<SetStateAction<StreakData>>;
  setAchievementRecord: Dispatch<SetStateAction<AchievementRecord>>;
}

export function useNutritionState({
  userBio,
  nutritionTargets,
  planState,
  currentDate,
  userGoals,
  todayDiet,
  waterMl,
  setTodayDiet,
  setDietHistory,
  setPlanState,
  setWaterMl,
  setStreakData,
  setAchievementRecord,
}: Params) {
  // Consumed nutrition derived from the schedule's isConsumed flags (SSOT).
  const consumedNutrition: ConsumedNutrition = useMemo(() => {
    if (!todayDiet?.schedule) {
      return { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, waterMl };
    }
    const n = calculateConsumedNutrition(todayDiet.schedule);
    return { ...n, waterMl };
  }, [todayDiet?.schedule, waterMl]);

  const refreshTodayDiet = useCallback(async () => {
    const diet = await getTodayDiet();
    setTodayDiet(diet);
  }, []);

  const refreshDietHistory = useCallback(async () => {
    const history = await getDietHistory();
    setDietHistory(history);
  }, []);

  const autoGenerateDietPlan = useCallback(
    async (dietId?: string) => {
      if (!userBio || !nutritionTargets) return;
      const bio = userBio;
      const targets = nutritionTargets;
      const today = todayDate();

      // Explicit "regenerate today" → force a fresh plan (AI-first via the
      // backend, local deterministic fallback) ignoring any cached day.
      const result = await regenerateDietForDate(bio, targets, today, dietId);
      if (result) {
        const newPlanState: PlanState = {
          ...planState,
          activeDietId: result.dietId,
          dateStamp: today,
          lastGeneratedAt: new Date().toISOString(),
          needsRegen: false,
          regenReason: null,
        };
        setPlanState(newPlanState);
        await writeJSON(KEYS.PLAN_STATE, newPlanState);
        await refreshTodayDiet();
        // Refresh the offline buffer for the days ahead in this style (online only).
        void ensureDietBuffer(bio, targets, today, dietId ?? result.dietId);
      }
    },
    [userBio, nutritionTargets, planState, refreshTodayDiet],
  );

  /**
   * Schedule a diet for the whole current week. Generates a deterministic
   * day plan for each date (Mon–Sun) via the same generator as the daily
   * path, persists each day, and records the active diet in planState so the
   * choice survives day-changes.
   */
  const scheduleWeeklyDietPlan = useCallback(
    async (dietId?: string) => {
      if (!userBio || !nutritionTargets) return;
      const bio = userBio;
      const targets = nutritionTargets;
      const weekStart = currentWeekStart();
      const monday = parseLocalDate(weekStart);
      const dates: string[] = [];
      for (let i = 0; i < 7; i++) {
        const d = new Date(monday);
        d.setDate(monday.getDate() + i);
        dates.push(toLocalDateString(d));
      }

      // Force-generate all 7 days (AI-first per day, local fallback) in parallel
      // and cache them so the entire week is available offline.
      const results = await Promise.all(
        dates.map((date) => regenerateDietForDate(bio, targets, date, dietId)),
      );
      const chosenDietId = results.find((r) => r)?.dietId ?? null;

      const newPlanState: PlanState = {
        ...planState,
        activeDietId: chosenDietId,
        weekStartDate: weekStart,
        dateStamp: todayDate(),
        lastGeneratedAt: new Date().toISOString(),
        needsRegen: false,
        regenReason: null,
      };
      setPlanState(newPlanState);
      await writeJSON(KEYS.PLAN_STATE, newPlanState);
      await refreshTodayDiet();
    },
    [userBio, nutritionTargets, planState, refreshTodayDiet],
  );

  /**
   * Mark a meal as consumed. No manual addNutrition — consumed totals
   * are derived from the schedule's isConsumed flags via useMemo.
   */
  const markMealAsConsumed = useCallback(
    async (
      mealType: "breakfast" | "lunch" | "dinner" | "snack",
      snackIndex?: number,
    ) => {
      await markMealConsumed(currentDate, mealType, snackIndex);
      await refreshTodayDiet();
      // Record activity for streaks
      const { data: updatedStreak } = await recordActivity(currentDate);
      setStreakData(updatedStreak);
    },
    [currentDate, refreshTodayDiet],
  );

  /**
   * Toggle a meal's consumed status (mark/unmark).
   * Consumed totals are re-derived automatically via useMemo.
   */
  const handleToggleMealConsumed = useCallback(
    async (
      mealType: "breakfast" | "lunch" | "dinner" | "snack",
      snackIndex?: number,
    ) => {
      await toggleMealConsumed(currentDate, mealType, snackIndex);
      await refreshTodayDiet();
    },
    [currentDate, refreshTodayDiet],
  );

  /**
   * Swap a meal in today's schedule with a different option.
   */
  const handleSwapMeal = useCallback(
    async (
      mealType: "breakfast" | "lunch" | "dinner" | "snack",
      newMeal: ScheduledMeal,
      snackIndex?: number,
    ) => {
      await swapMealInSchedule(currentDate, mealType, newMeal, snackIndex);
      await refreshTodayDiet();
    },
    [currentDate, refreshTodayDiet],
  );

  /**
   * Log a single whole food from the Foods catalog as a consumed snack on
   * today's plan. Mirrors markMealAsConsumed's streak credit. Returns false if
   * there's no scheduled diet for today to attach it to.
   */
  const addFoodAsSnack = useCallback(
    async (food: FoodItem): Promise<boolean> => {
      const meal: ScheduledMeal = {
        id: `food_${food.id}_${Date.now()}`,
        mealType: "snack",
        name: food.serving ? `${food.name} (${food.serving})` : food.name,
        calories: { min: food.calories, max: food.calories },
        proteinG: { min: food.protein, max: food.protein },
        carbsG: { min: food.carbs, max: food.carbs },
        fatG: { min: food.fat, max: food.fat },
        isNigerian: food.isNigerian,
        cuisine: food.cuisine,
        isConsumed: true,
        consumedAt: new Date().toISOString(),
      };
      const ok = await addSnackToSchedule(currentDate, meal);
      if (ok) {
        await refreshTodayDiet();
        const { data: updatedStreak } = await recordActivity(currentDate);
        setStreakData(updatedStreak);
      }
      return ok;
    },
    [currentDate, refreshTodayDiet],
  );

  const addWater = useCallback(
    (ml: number) => {
      const goal =
        userGoals?.dailyWaterMl ?? nutritionTargets?.waterMl ?? 2500;
      setWaterMl((prev) => {
        const next = prev + ml;
        writeJSON(KEYS.WATER_TODAY, next);
        // Credit a hydration-goal day the moment today's intake first crosses
        // the goal (deduped per day inside creditWaterGoalDay). This is the one
        // achievement signal not already captured elsewhere.
        if (prev < goal && next >= goal) {
          const today = todayDate();
          setAchievementRecord((rec) => {
            const updated = creditWaterGoalDay(rec, today);
            if (updated !== rec) saveAchievementRecord(updated);
            return updated;
          });
        }
        return next;
      });
    },
    [userGoals, nutritionTargets],
  );

  return {
    consumedNutrition,
    refreshTodayDiet,
    refreshDietHistory,
    autoGenerateDietPlan,
    scheduleWeeklyDietPlan,
    markMealAsConsumed,
    handleToggleMealConsumed,
    handleSwapMeal,
    addFoodAsSnack,
    addWater,
  };
}
