/**
 * PeriodReportService — the "your plan has ended, here's how it went" report.
 *
 * DETERMINISTIC BY CONSTRUCTION. Every figure is computed from stored history
 * (DIET_HISTORY rows and body logs); nothing is generated by a model and
 * nothing is sampled. Run it twice on the same data and you get byte-identical
 * output, which is what makes it safe to cache, to archive, and to show a user
 * as a record of what they actually did.
 *
 * The headline and highlights are chosen from the numbers by fixed rules — the
 * copy is written here, the *selection* is arithmetic. A user who skipped every
 * breakfast is told exactly that, because the data says so, not because a model
 * decided that was an interesting angle.
 *
 * WHAT IT DELIBERATELY DOESN'T DO
 * It doesn't fill gaps. Days with no plan are counted as `empty` and excluded
 * from adherence rather than counted as failures — a custom-mode user who
 * planned four days out of seven adhered to four days, not four-sevenths.
 */

import type { DietHistoryEntry, MealType } from "../models/diet";
import {
  daysBetween,
  periodDays,
  periodLengthDays,
  type DayOutcome,
  type MealPlanPeriod,
  type PeriodReport,
  type SlotAdherence,
} from "../models/mealPlan";
import type { BodyLogEntry } from "../models/workout";
import { KEYS, readJSON, writeJSON } from "./OfflineStorage";

const SLOTS: MealType[] = ["breakfast", "lunch", "dinner", "snack"];

const SLOT_LABEL: Record<MealType, string> = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snacks",
};

export interface BuildReportInput {
  period: MealPlanPeriod;
  history: DietHistoryEntry[];
  bodyLogs: BodyLogEntry[];
  /** Daily targets in force during the period, for the vs-target comparison. */
  targets?: {
    calories?: number;
    proteinG?: number;
    carbsG?: number;
    fatG?: number;
  };
}

/**
 * Build the report for a period. Pure — takes everything it needs as input so
 * it can be tested without storage and re-run cheaply.
 */
export function buildPeriodReport(input: BuildReportInput): PeriodReport {
  const { period, history, bodyLogs } = input;
  // The days the plan actually covered — for a menu built from picked dates
  // that's those dates, not every day in between, or the gaps the user never
  // planned would be reported as days they failed to eat.
  const dates = periodDays(period);
  const byDate = new Map(history.map((h) => [h.date, h]));

  // --- Day-by-day outcomes ------------------------------------------------
  const days: DayOutcome[] = dates.map((date) => {
    const entry = byDate.get(date);
    if (!entry || entry.totalMeals === 0) {
      return { date, planned: 0, consumed: 0, empty: true };
    }
    return {
      date,
      planned: entry.totalMeals,
      consumed: entry.mealsConsumed,
      empty: false,
      ...(entry.consumedCalories !== undefined
        ? { calories: entry.consumedCalories }
        : {}),
    };
  });

  const planned = days.filter((d) => !d.empty);
  const mealsPlanned = planned.reduce((sum, d) => sum + d.planned, 0);
  const mealsConsumed = planned.reduce((sum, d) => sum + d.consumed, 0);
  const adherenceRate = mealsPlanned > 0 ? mealsConsumed / mealsPlanned : 0;

  // --- Per-slot adherence -------------------------------------------------
  // Derived from the meal-name lists rather than a slot field, because that's
  // what history actually stores. Slot is inferred from the entry's structure:
  // we count what was consumed vs skipped across the period per position.
  const perSlot = computePerSlot(planned, history);

  // --- Which meals worked and which didn't --------------------------------
  const skippedTally = new Map<string, number>();
  const eatenTally = new Map<string, number>();
  for (const date of dates) {
    const entry = byDate.get(date);
    if (!entry) continue;
    for (const name of entry.skippedMeals ?? []) {
      skippedTally.set(name, (skippedTally.get(name) ?? 0) + 1);
    }
    for (const name of entry.consumedMeals ?? []) {
      eatenTally.set(name, (eatenTally.get(name) ?? 0) + 1);
    }
  }
  const mostSkipped = topN(skippedTally, 5);
  const mostEaten = topN(eatenTally, 5);

  // --- Streaks & day quality ----------------------------------------------
  let bestStreakDays = 0;
  let running = 0;
  let perfectDays = 0;
  let missedDays = 0;
  for (const day of days) {
    if (day.empty) {
      // A day with no plan neither builds nor breaks a streak — there was
      // nothing to adhere to.
      continue;
    }
    if (day.consumed > 0 && day.consumed === day.planned) {
      perfectDays++;
      running++;
      bestStreakDays = Math.max(bestStreakDays, running);
    } else {
      if (day.consumed === 0) missedDays++;
      running = 0;
    }
  }

  // --- Nutrition averages -------------------------------------------------
  const withMacros = dates
    .map((d) => byDate.get(d))
    .filter(
      (e): e is DietHistoryEntry =>
        !!e && e.totalMeals > 0 && e.consumedCalories !== undefined,
    );

  const avgConsumed = {
    calories: average(withMacros.map((e) => e.consumedCalories!)),
    proteinG: average(withMacros.map((e) => e.consumedProteinG ?? null)),
    carbsG: average(withMacros.map((e) => e.consumedCarbsG ?? null)),
    fatG: average(withMacros.map((e) => e.consumedFatG ?? null)),
  };

  const targets = {
    calories: input.targets?.calories ?? period.baseline.targetCalories ?? null,
    proteinG: input.targets?.proteinG ?? period.baseline.targetProteinG ?? null,
    carbsG: input.targets?.carbsG ?? period.baseline.targetCarbsG ?? null,
    fatG: input.targets?.fatG ?? period.baseline.targetFatG ?? null,
  };

  const vsTarget = {
    calories: delta(avgConsumed.calories, targets.calories),
    proteinG: delta(avgConsumed.proteinG, targets.proteinG),
    carbsG: delta(avgConsumed.carbsG, targets.carbsG),
    fatG: delta(avgConsumed.fatG, targets.fatG),
  };

  // --- Weight change ------------------------------------------------------
  const weight = computeWeightChange(period, bodyLogs);

  // --- Verdict & narrative ------------------------------------------------
  const totalDays = periodLengthDays(period);
  const verdict = pickVerdict(adherenceRate, planned.length);
  const headline = buildHeadline(verdict, adherenceRate, period);
  const highlights = buildHighlights({
    period,
    adherenceRate,
    perfectDays,
    missedDays,
    bestStreakDays,
    perSlot,
    mostSkipped,
    mostEaten,
    avgConsumed,
    targets,
    vsTarget,
    weight,
    daysWithPlan: planned.length,
    totalDays,
  });

  return {
    periodId: period.id,
    label: period.label,
    mode: period.mode,
    dietId: period.dietId,
    dietName: period.dietName,
    startDate: period.startDate,
    endDate: period.endDate,
    daysWithPlan: planned.length,
    totalDays,
    mealsPlanned,
    mealsConsumed,
    mealsSkipped: mealsPlanned - mealsConsumed,
    adherenceRate,
    perSlot,
    mostSkipped,
    mostEaten,
    bestStreakDays,
    perfectDays,
    missedDays,
    avgConsumed,
    targets,
    vsTarget,
    weight,
    days,
    verdict,
    headline,
    highlights,
    generatedAt: new Date().toISOString(),
  };
}

// ============================================================================
// PIECES
// ============================================================================

/**
 * Per-slot adherence. History stores meal NAMES by outcome, not slots, so we
 * reconstruct slot-level rates from mealTimes (which is keyed by slot) where
 * available, and otherwise fall back to distributing the day's outcome evenly.
 * The fallback is flagged by a planned count of 0 so the UI can hide a slot we
 * genuinely can't speak to.
 */
function computePerSlot(
  plannedDays: DayOutcome[],
  history: DietHistoryEntry[],
): SlotAdherence[] {
  const byDate = new Map(history.map((h) => [h.date, h]));
  const tally = new Map<MealType, { planned: number; consumed: number }>(
    SLOTS.map((s) => [s, { planned: 0, consumed: 0 }]),
  );

  for (const day of plannedDays) {
    const entry = byDate.get(day.date);
    if (!entry) continue;
    const times = entry.mealTimes;
    // mealTimes only records slots that were EATEN. Combined with the day's
    // planned count we can attribute consumption precisely; slots we can't
    // attribute are left out rather than guessed at.
    if (times) {
      for (const slot of SLOTS) {
        const bucket = tally.get(slot)!;
        if (times[slot] !== undefined) {
          bucket.planned++;
          bucket.consumed++;
        }
      }
    }
    // Skipped meals can't be attributed to a slot from names alone, so the
    // planned side is topped up from the day's totals across main meals.
    const unattributed = entry.totalMeals - (times ? Object.keys(times).length : 0);
    if (unattributed > 0) {
      // Distribute across the three main slots in order — the generator always
      // fills breakfast/lunch/dinner before snacks.
      let remaining = unattributed;
      for (const slot of ["breakfast", "lunch", "dinner"] as MealType[]) {
        if (remaining <= 0) break;
        const bucket = tally.get(slot)!;
        if (times?.[slot] === undefined) {
          bucket.planned++;
          remaining--;
        }
      }
      if (remaining > 0) tally.get("snack")!.planned += remaining;
    }
  }

  return SLOTS.map((slot) => {
    const { planned, consumed } = tally.get(slot)!;
    return {
      slot,
      planned,
      consumed,
      rate: planned > 0 ? consumed / planned : 0,
    };
  }).filter((s) => s.planned > 0);
}

function computeWeightChange(
  period: MealPlanPeriod,
  bodyLogs: BodyLogEntry[],
): PeriodReport["weight"] {
  const inWindow = bodyLogs
    .filter((l) => l.date >= period.startDate && l.date <= period.endDate)
    .sort((a, b) => a.date.localeCompare(b.date));

  // Prefer the baseline captured when the period started; fall back to the
  // first weigh-in inside the window.
  const startKg = period.baseline.weightKg ?? inWindow[0]?.weightKg ?? null;
  const endKg = inWindow.length > 0 ? inWindow[inWindow.length - 1].weightKg : null;

  if (startKg === null || endKg === null) {
    return { startKg, endKg, deltaKg: null, perWeekKg: null };
  }

  const deltaKg = round(endKg - startKg, 1);
  // Normalise by the span actually covered by weigh-ins, so a 3-day period and
  // a 3-month one are directly comparable.
  const spanDays = Math.max(
    1,
    inWindow.length > 1
      ? daysBetween(inWindow[0].date, inWindow[inWindow.length - 1].date)
      : periodLengthDays(period),
  );
  return {
    startKg: round(startKg, 1),
    endKg: round(endKg, 1),
    deltaKg,
    perWeekKg: round((deltaKg / spanDays) * 7, 2),
  };
}

function pickVerdict(
  rate: number,
  daysWithPlan: number,
): PeriodReport["verdict"] {
  if (daysWithPlan === 0) return "insufficient-data";
  if (rate >= 0.9) return "excellent";
  if (rate >= 0.7) return "good";
  if (rate >= 0.4) return "mixed";
  return "struggled";
}

function buildHeadline(
  verdict: PeriodReport["verdict"],
  rate: number,
  period: MealPlanPeriod,
): string {
  const pct = Math.round(rate * 100);
  const name = period.dietName ?? period.label;
  switch (verdict) {
    case "excellent":
      return `You finished ${name} at ${pct}% — that's a strong run.`;
    case "good":
      return `You completed ${name} at ${pct}%. Solid, with room to tighten up.`;
    case "mixed":
      return `${name} came in at ${pct}%. Some days landed, others didn't.`;
    case "struggled":
      return `${name} finished at ${pct}%. This one didn't fit — worth trying a different approach.`;
    case "insufficient-data":
      return `${name} ended without enough logged days to score.`;
  }
}

interface HighlightInput {
  period: MealPlanPeriod;
  adherenceRate: number;
  perfectDays: number;
  missedDays: number;
  bestStreakDays: number;
  perSlot: SlotAdherence[];
  mostSkipped: { name: string; times: number }[];
  mostEaten: { name: string; times: number }[];
  avgConsumed: PeriodReport["avgConsumed"];
  targets: PeriodReport["targets"];
  vsTarget: PeriodReport["vsTarget"];
  weight: PeriodReport["weight"];
  daysWithPlan: number;
  totalDays: number;
}

/**
 * Turn the numbers into plain observations. Each rule fires only when its
 * threshold is genuinely met, so the list stays short and every line is
 * something the user could verify themselves from the same data.
 */
function buildHighlights(i: HighlightInput): string[] {
  const out: string[] = [];

  if (i.daysWithPlan === 0) {
    return ["No days in this period had a plan, so there's nothing to score."];
  }

  if (i.bestStreakDays >= 3) {
    out.push(`Best run: ${i.bestStreakDays} days in a row with every meal logged.`);
  }
  if (i.perfectDays > 0) {
    out.push(
      `${i.perfectDays} of ${i.daysWithPlan} planned days were completed in full.`,
    );
  }

  // The most actionable single fact: the slot you reliably miss.
  const weakest = [...i.perSlot].sort((a, b) => a.rate - b.rate)[0];
  if (weakest && weakest.rate < 0.6 && weakest.planned >= 3) {
    out.push(
      `${cap(SLOT_LABEL[weakest.slot])} was your weak spot — logged ${Math.round(
        weakest.rate * 100,
      )}% of the time.`,
    );
  }
  const strongest = [...i.perSlot].sort((a, b) => b.rate - a.rate)[0];
  if (strongest && strongest.rate >= 0.9 && strongest.planned >= 3 && strongest !== weakest) {
    out.push(`You never missed ${SLOT_LABEL[strongest.slot]} — that habit is stuck.`);
  }

  if (i.mostSkipped[0] && i.mostSkipped[0].times >= 2) {
    out.push(
      `"${i.mostSkipped[0].name}" went uneaten ${i.mostSkipped[0].times} times. Worth swapping out next round.`,
    );
  }
  if (i.mostEaten[0] && i.mostEaten[0].times >= 3) {
    out.push(`"${i.mostEaten[0].name}" was your most-eaten meal (${i.mostEaten[0].times}×).`);
  }

  // Calories vs target, but only when we have both and the gap is meaningful.
  if (i.avgConsumed.calories !== null && i.targets.calories && i.vsTarget.calories !== null) {
    const gap = i.vsTarget.calories;
    if (Math.abs(gap) >= 150) {
      out.push(
        gap > 0
          ? `You averaged ${Math.round(i.avgConsumed.calories)} kcal — about ${Math.round(gap)} over your ${i.targets.calories} target.`
          : `You averaged ${Math.round(i.avgConsumed.calories)} kcal — about ${Math.abs(Math.round(gap))} under your ${i.targets.calories} target.`,
      );
    } else {
      out.push(
        `You held close to your calorie target, averaging ${Math.round(i.avgConsumed.calories)} kcal.`,
      );
    }
  }

  if (i.avgConsumed.proteinG !== null && i.targets.proteinG) {
    const pct = Math.round((i.avgConsumed.proteinG / i.targets.proteinG) * 100);
    if (pct < 80) {
      out.push(`Protein averaged ${Math.round(i.avgConsumed.proteinG)}g — ${pct}% of target.`);
    }
  }

  if (i.weight.deltaKg !== null && Math.abs(i.weight.deltaKg) >= 0.3) {
    const dir = i.weight.deltaKg < 0 ? "down" : "up";
    out.push(
      `Weight ${dir} ${Math.abs(i.weight.deltaKg)}kg over the period (${i.weight.startKg} → ${i.weight.endKg}kg).`,
    );
  } else if (i.weight.deltaKg === null) {
    out.push("No weigh-ins were logged, so body change couldn't be measured.");
  }

  const emptyDays = i.totalDays - i.daysWithPlan;
  if (emptyDays > 0 && i.period.mode === "custom") {
    out.push(
      `${emptyDays} of ${i.totalDays} days had no meals planned — those aren't counted against you.`,
    );
  }

  return out;
}

// ============================================================================
// UTILITIES
// ============================================================================

function topN(tally: Map<string, number>, n: number) {
  return Array.from(tally.entries())
    .map(([name, times]) => ({ name, times }))
    .sort((a, b) => b.times - a.times || a.name.localeCompare(b.name))
    .slice(0, n);
}

function average(values: (number | null)[]): number | null {
  const nums = values.filter((v): v is number => typeof v === "number");
  if (nums.length === 0) return null;
  return round(nums.reduce((a, b) => a + b, 0) / nums.length, 1);
}

function delta(actual: number | null, target: number | null): number | null {
  if (actual === null || target === null) return null;
  return round(actual - target, 1);
}

function round(n: number, dp: number): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ============================================================================
// PERSISTENCE
// ============================================================================
// Reports are cached once their period is closed. A closed period's history can
// no longer change (the back-log window has passed), so the cached report is
// permanently accurate — and the archive stays readable without recomputing.

type ReportCache = Record<string, PeriodReport>;

export async function getCachedReport(
  periodId: string,
): Promise<PeriodReport | null> {
  const cache = await readJSON<ReportCache>(KEYS.PERIOD_REPORTS, {});
  return cache[periodId] ?? null;
}

export async function cacheReport(report: PeriodReport): Promise<void> {
  const cache = await readJSON<ReportCache>(KEYS.PERIOD_REPORTS, {});
  cache[report.periodId] = report;
  await writeJSON(KEYS.PERIOD_REPORTS, cache);
}

/**
 * Get a period's report, computing and caching it on first request. Pass
 * `force` to recompute a still-running period, whose numbers are still moving.
 */
export async function getOrBuildReport(
  input: BuildReportInput,
  force = false,
): Promise<PeriodReport> {
  const isClosed =
    input.period.status === "completed" || input.period.status === "ended-early";
  if (!force && isClosed) {
    const cached = await getCachedReport(input.period.id);
    if (cached) return cached;
  }
  const report = buildPeriodReport(input);
  if (isClosed) await cacheReport(report);
  return report;
}
